# version: "3.8"

services:
  django:
    build: .
    container_name: RAG_CHATBOT_APP
    restart: always
    depends_on:
      - db
    environment:
      DB_TYPE: mysql
      DB_NAME: RAG_CHATBOT
      DB_USER: root
      DB_PASSWORD: your_new_password
      DB_HOST: db
      DB_PORT: 3306
    ports:
      - "8000:8000"
    volumes:
      - .:/app

  db:
    image: mysql:8.0
    container_name: RAG_CHATBOT_APP_mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: your_new_password
      MYSQL_DATABASE: RAG_CHATBOT
      MYSQL_USER: root
      MYSQL_PASSWORD: your_new_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  nginx:
    image: nginx:latest
    container_name: RAG_CHATBOT_APP_nginx_server
    restart: always
    ports:
      - "80:80"
    depends_on:
      - django
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro

volumes:
  mysql_data:
