"""
Django settings for RAG_Backend project.

Generated by 'django-admin startproject' using Django 5.1.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import os
from pathlib import Path
from dotenv import load_dotenv
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
import pymysql
pymysql.install_as_MySQLdb()
AUTH_USER_MODEL = 'RAG_CHATBOT_BACKEND_APIS.CustomUser'
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-4rui8%q0xhb&$s3ju5-yp^j0i5&@i(pyrople(9y^9g723q@5y'
BASE_API_URL = os.getenv("BASE_API_URL", "http://127.0.0.1:8000")  # Default to localhost
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
ALLOWED_HOSTS = ['*']
BASE_DIR = Path(__file__).resolve().parent.parent
STATIC_URL = '/static/'
STATICFILES_DIRS = [
    # os.path.join(BASE_DIR, "static"),
    os.path.join(BASE_DIR, 'RAG_CHATBOT_BACKEND_APIS/static'),
]
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
# Application definition
APPEND_SLASH =False
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media/uploads/')
MEDIA_URL = '/media/'

# Ensure the directory exists
if not os.path.exists(MEDIA_ROOT):
    os.makedirs(MEDIA_ROOT)
# Ensure this is added in DEBUG mode only
if DEBUG:
    from django.conf.urls.static import static
    MEDIA_URL = '/media/'
    MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'RAG_CHATBOT_BACKEND_APIS',
    'rest_framework_swagger',
    'drf_yasg',
    'django.contrib.humanize'
    
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'RAG_Backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')], 
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                 'django.template.context_processors.media',
            ],
        },
    },
]

WSGI_APPLICATION = 'RAG_Backend.wsgi.application'

load_dotenv()
DB_TYPE = os.getenv('DB_TYPE')
OPENAI_API_KEY = os.getenv('OPENAI_API_KEY')

# 
# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases
# __import__('pysqlite3')
# import sys

# sys.modules['sqlite3'] = sys.modules.pop('pysqlite3')


if DB_TYPE == 'sqlite3':
    print('Using SQLite3')
    DATABASES = {
    "default": { "ENGINE": "django.db.backends.sqlite3", "NAME": BASE_DIR / "db.sqlite3", }  }
else:
    print('Using MySQL')
    DATABASES = {
        'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': os.getenv('DB_NAME'),
        'USER': os.getenv('DB_USER'),
        'PASSWORD': os.getenv('DB_PASSWORD'),
        'HOST': os.getenv('DB_HOST'),
        'PORT': os.getenv('DB_PORT'),
        'OPTIONS': {
            'charset': 'utf8mb4',
            # 'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
        }
    }
    }
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = "smtp.hostinger.com"
EMAIL_PORT = 465
EMAIL_USE_SSL = True  # Since we use port 465
EMAIL_USE_TLS = False  # Must be False when using SSL
EMAIL_HOST_USER = "pythonweb@exoticaitsolutions.com"
EMAIL_HOST_PASSWORD = "Webpython@123#"  # Ensure this is correct
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER

# EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
# EMAIL_HOST = os.getenv("EMAIL_HOST", "smtp.gmail.com")
# EMAIL_PORT = int(os.getenv("EMAIL_PORT", 587))
# EMAIL_USE_TLS = os.getenv("EMAIL_USE_TLS", "True") == "True"
# EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER", "pk@12gmail.com")
# EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD", "Prateek@123")


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValgit idator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# settings.py


# settings.py

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'level': 'INFO',  # Log level (e.g., DEBUG, INFO, WARNING, ERROR, CRITICAL)
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
        'file': {
            'level': 'INFO',  # Log level
            'class': 'logging.FileHandler',
            'filename': 'django_debug.log',  # Log file location
            'formatter': 'verbose',
        },
    },
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'file'],  # Log to console and file
            'level': 'INFO',  # Log level (DEBUG, INFO, WARNING, ERROR, CRITICAL)
            'propagate': True,
        },
    },
}
LOGIN_URL = '/login/'
# BASE_API_URL = "http://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.com"

BASE_API_URL = "http://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.com"


SESSION_ENGINE = "django.contrib.sessions.backends.db"  #  Ensure this is set
SESSION_COOKIE_AGE = 1209600  # adjust as needed
SESSION_EXPIRE_AT_BROWSER_CLOSE = False
SESSION_SAVE_EVERY_REQUEST = True
<<<<<<< HEAD

# AUTH_USER_MODEL = 'rag_chatbot_backend_apis.CustomUser'
=======
APPEND_SLASH = True
CSRF_TRUSTED_ORIGINS = [
    "http://127.0.0.1:8000",  # Localhost
    "http://localhost:8000",
    "https://yourdomain.com",  # Add your production domain if needed
]


EMAIL_HOST_USER = "pythonweb@exoticaitsolutions.com"
DEFAULT_FROM_EMAIL = "pythonweb@exoticaitsolutions.com"
SERVER_EMAIL = "pythonweb@exoticaitsolutions.com"
# Session expires after 30 minutes of inactivity
SESSION_COOKIE_AGE = 1800  # 30 minutes in seconds
SESSION_EXPIRE_AT_BROWSER_CLOSE = False  # Logout on browser close
SESSION_SAVE_EVERY_REQUEST = True  # Reset session timer on activity
>>>>>>> 4f2ff96ff6e59c1ed95fb7570ec6a2164f6e9406
