# Generated by Django 5.1.6 on 2025-02-10 10:44

import RAG_CHATBOT_BACKEND_APIS.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatbotAppearance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chatbot_id', models.CharField(max_length=50)),
                ('display_name', models.TextField(max_length=2000)),
                ('footer_name', models.TextField(default='Powered by My AI Solutions.', max_length=2000)),
                ('initial_message', models.TextField(blank=True, default='Hi! What can I help with you?')),
                ('chatbot_theme', models.CharField(blank=True, default='#8d54a2', max_length=10)),
                ('chatbot_mode', models.BooleanField(default=False)),
                ('suggested_messages', models.TextField(blank=True)),
                ('chatbot_image', models.ImageField(blank=True, default='default_images/chatbot_image.png', null=True, upload_to='chatbot_images/')),
                ('chatbot_launcher_icon', models.ImageField(blank=True, default='default_images/avatar-1.png', null=True, upload_to='launcher_icon/')),
                ('top_bar_background', models.CharField(default='#8d54a2', max_length=10)),
                ('top_bar_textcolor', models.CharField(default='#000000', max_length=10)),
                ('bot_message_background', models.CharField(default='#ffffff', max_length=10)),
                ('bot_message_color', models.CharField(default='#46464e', max_length=10)),
                ('user_message_background', models.CharField(default='#ffffff', max_length=10)),
                ('user_message_color', models.CharField(default='#46464e', max_length=10)),
                ('chatbot_background_color', models.CharField(default='#e6e6e6', max_length=10)),
                ('chatbot_background_pattern', models.ImageField(blank=True, upload_to='chatbot_background_patterns/')),
                ('font_family', models.CharField(default='Arial', max_length=255)),
                ('font_size', models.PositiveIntegerField(blank=True, default=14)),
                ('widget_width', models.PositiveIntegerField(blank=True, default=25)),
                ('widget_height', models.PositiveIntegerField(blank=True, default=450)),
                ('widget_position', models.CharField(default='right', max_length=5)),
                ('show_popup_notification', models.BooleanField(default=True)),
                ('delay_showing_popup_notification', models.PositiveIntegerField(default=1)),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pdf_embedding_status', models.CharField(default='pending', max_length=20)),
                ('pdf_embadding_error_or_message', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UrlUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('url_embedding_status', models.CharField(default='pending', max_length=50)),
                ('url_embedding_error_or_message', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChatBotDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chatbot_name', models.CharField(max_length=200)),
                ('llm_model', models.CharField(choices=[('system openai', 'System OpenAi'), ('private openai', 'Private OpenAi'), ('gpt4all', 'GPT4ALL'), ('huggingface', 'HuggingFace')], default='system openai', max_length=50)),
                ('model', models.CharField(choices=[('gpt-3.5-turbo', 'gpt-3.5-turbo'), ('gpt-4', 'gpt-4')], default='gpt-3.5-turbo', max_length=50)),
                ('openai_key', models.TextField(default='')),
                ('vector_database', models.CharField(choices=[('chroma', 'Chroma'), ('pinecone', 'Pinecone')], default='chroma', max_length=200)),
                ('pinecone_key', models.CharField(default='', max_length=200)),
                ('pinecone_env', models.TextField(default='')),
                ('pinecone_user_index', models.CharField(default='', max_length=200)),
                ('temperature', models.FloatField(default=0.4)),
                ('context', models.TextField(default="You are a conversational chatbot and Use the following pieces of context to answer the question at the end. You will try your best to give a logical answer. If you don't know the answer, just say that you don't know, don't try to make up an answer")),
                ('chatbot_id', models.CharField(max_length=50)),
                ('hits', models.PositiveIntegerField(default=10)),
                ('seconds', models.PositiveIntegerField(default=60)),
                ('visibility', models.CharField(default='private', max_length=50)),
                ('login_status', models.CharField(choices=[('anonymous', 'Anonymous'), ('login', 'Login')], default='login', max_length=20)),
                ('icon_url', models.ImageField(default='/media/default_images/chatbot_image.png', upload_to='chatbot')),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chatbot_appearance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RAG_CHATBOT_BACKEND_APIS.chatbotappearance')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filepath', models.FileField(upload_to=RAG_CHATBOT_BACKEND_APIS.models.Document.upload_path)),
                ('name', models.CharField(default='', max_length=250)),
                ('size', models.CharField(default='', max_length=250)),
                ('no_of_characters', models.PositiveIntegerField(blank=True, default=0)),
                ('no_of_chunks', models.PositiveIntegerField(blank=True, default=0)),
                ('status', models.CharField(default='pending', max_length=10)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now_add=True)),
                ('chatbot', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='RAG_CHATBOT_BACKEND_APIS.chatbotdb')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentCollectionIds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_id', models.CharField(default='', max_length=100)),
                ('doc_name', models.CharField(default='', max_length=500)),
                ('collection', models.CharField(default='', max_length=100)),
                ('chroma_dir', models.CharField(default='', max_length=100)),
                ('chatbot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RAG_CHATBOT_BACKEND_APIS.chatbotdb')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RAG_CHATBOT_BACKEND_APIS.document')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentNamespaceIds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_id', models.CharField(default='', max_length=100)),
                ('doc_name', models.CharField(default='', max_length=500)),
                ('namespace', models.CharField(default='', max_length=100)),
                ('index_name', models.CharField(default='None', max_length=100)),
                ('chatbot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RAG_CHATBOT_BACKEND_APIS.chatbotdb')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RAG_CHATBOT_BACKEND_APIS.document')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
